### ISSUE TITLE
Research on CourtListener Data

### ISSUE THREAD

**Issue by eshanprashar** [eshanprashar/judges-conflicts#1]
### Context of the Project:
From https://docs.google.com/document/d/1w33JdFcSCV5J2qOVfYBk-q6hlB9HugVuEolprYrLXLg/edit?pli=1
_District courts have exclusive legal power to make final decisions in patent ownership and infringement lawsuits. This paper shows that when district courts systematically favor plaintiffs over defendants, their biased attitudes stifle innovation and reduce the financial value of firms under their jurisdiction. To arrive at this conclusion, we exploit the 2017 Supreme Court ruling that limits the venues where plaintiffs can file a patent litigation case to defendants' local district courts only. Firms which, following the ruling, have become subject to the jurisdiction of plaintiff-friendly district courts generate fewer patents with lower total market value and invest less in R&D compared to firms subject to the jurisdiction of defendant-friendly district courts._

### In simple terms (from Chat-GPT):
Consider two imaginary entities: Jane, the plaintiff, and TechCorp, the defendant. Jane can financially benefit by betting that TechCorp's (the defendant's) stock price will drop before filing a lawsuit. This bet can turn a lawsuit that might cost Jane money into a profitable situation if TechCorp's stock price falls. Depending on how aggressively Jane bets against TechCorp's stock, it can either hurt TechCorp more or encourage them to settle the case quickly.

Investigative journalism that leverages and covers financial disclosures:
1. [WSJ article, paywall](https://www.wsj.com/articles/131-federal-judges-broke-the-law-by-hearing-cases-where-they-had-a-financial-interest-11632834421?st=wm0bzo39zzjts1v)

2. [Web archives](https://web.archive.org/web/20190614103410/https://famguardian.org/PublishedAuthors/Media/KCStar/30da0058.404,.htm)

WSJ article, downloaded pdf: 
[wsj_article_CL_data_131 Federal Judges Broke the Law by Hearing Cases Where They Had a Financial Interest - WSJ.pdf](https://github.com/user-attachments/files/15956618/wsj_article_CL_data_131.Federal.Judges.Broke.the.Law.by.Hearing.Cases.Where.They.Had.a.Financial.Interest.-.WSJ.pdf)
[Uploading wsj_article_methodology.pdf…]()

**Tasks on June 17, 2024:**
- [x] Explore CourtListener website structure and data
- [x] [Skim Rand paper](https://www.jstor.org/stable/2555827?casa_token=FTW_jLK6DsQAAAAA%3AklQi_thXEd8JHN5Wx__O_ejjv5htpPSPmhdeskhvJyEsIAOGQ5C7aie2YrgViRczagkryZ_ibtt20sWc5fY-y3rVW4mpWri3EtJdWzs7tWTFgRAoONM)
- [x] Read the documentation for [Financial Disclosure APIs](https://www.courtlistener.com/help/api/rest/v3/financial-disclosures/)
- [x] Understand and simplify the ER diagram

**Tasks on July 3, 2024:**
- [ ] Get a download of Judges with history of positions (when did they become a judge) to have a cutoff time
- [ ] For a given judge, get the list of investments
- [ ] For a given judge, get the names of companies they voted on

**Comment by eshanprashar** [comment]
### CourtListener divides data into the following 6 categories:
1. Case Law: Searchable database of case files, with docket numbers. A user can download PDFs for a given case/docket and filing. From the [website](https://www.courtlistener.com/opinion/):
_We are particularly proud of our Supreme Court data, which we consider to be the best collection available. We have made thousands of corrections to the other publicly available data sets, and have enhanced it with data from the [Library of Congress](https://free.law/2011/05/25/updated-scotus-dates/) and the [Supreme Court Database](https://free.law/2014/12/21/scdb/)._

2. RECAP Archive: Collection of PACER documents
3. FJC Integrated Civil Data: The IDB contains data on civil case and criminal defendant filings and terminations in the district courts, along with bankruptcy court and appellate court case information from 1970 to the present. The FJC receives regular updates of the case-related data that are routinely reported by the courts to the AOUSC. The FJC then post-processes the data, consistent with the policies of the Judicial Conference of the United States governing access to these data, into a unified longitudinal database, the IDB.

4. Oral Arguments: Audio recordings of certain case files
5. Financial Disclosures: A database can be queried using a judge's name. For a judge, data across years on financial disclosures is shared in the following columns:
  - Description
  - Gross Value Code
  - Gross Value Method
  - Income Code
  - Income Type
  - Transaction Type
  - Transaction Date
  - Transaction Value
  - Transaction Gain

Example for [Lewis Thornton](https://www.courtlistener.com/person/145/disclosure/29043/lewis-thornton-babcock/), mentioned in the WSJ article linked above.

6. Judge names: Ability to find names and basic information of judges using a bunch of filters (date of birth, political leaning etc.)

**Comment by eshanprashar** [comment]
### Getting data from CourtListener
CourtListener has multiple ways of providing data [link](https://www.courtlistener.com/help/api/). For Financial Disclosures, the simplest way seems to be usage of REST APIs.

Next steps are:
- [ ] Read the documentation for [Financial Disclosure APIs](https://www.courtlistener.com/help/api/rest/v3/financial-disclosures/)
- [ ] Understand and simplify the ER diagram below:
![people-model-v3 13 e2c9764750a3](https://github.com/eshanprashar/judges-conflicts/assets/114944808/950e3863-a6f4-4012-b0b0-c0f25b3de165)

**Comment by eshanprashar** [comment]
### API Usage
**Source:** https://www.courtlistener.com/help/api/rest/#your-authorization-token

Our APIs allow 5,000 queries per hour to authenticated users. Unauthenticated users are allowed 100 queries per day for experimentation.

To debug throttling issues:

Try browsing the API while logged into the website. If this works and your code fails, it usually means that your token authentication is not configured properly, and your code is getting throttled as an anonymous user, not according to your token.
Review your recent API usage by looking in your [profile](https://www.courtlistener.com/profile/api/#usage), but remember that it will show stats for the browsable API as well.
Review the [authentication/throttling tips in our forum](https://github.com/freelawproject/courtlistener/discussions/1497).
If, after checking the above, you need your rate limit increased, [please get in touch](https://www.courtlistener.com/contact/) so we can help.

#### Performance Tips
A few things to consider that may increase your performance:

When doing deep crawls of the data, going to very high page numbers will incur increasingly bad performance. This is common in databases because to go to a high page number means sorting the entire data set, then counting to the correct location. Page 50 isn't a big deal. Page 2,000 starts getting slower.

The fix to this solution is often to work with "slices" of the data. Instead of paginating across the whole result set, use a date field or another range-type field to only paginate over a smaller set of the data. For example, you could slice a large result set by the month of the date filing field to prevent deep pagination.

Be careful to slice using a field with a normal distribution. Do not use one like date_created, which could have extreme spikes of activity.

Avoid doing queries like court__id=xyz when you can instead do court=xyz. Doing queries with the extra __id introduces a join that can be expensive.

In general, less data is easier and faster to get than more. Could you use a field to filter your result set down to something smaller?

When using the search endpoint, smaller result sets are faster. It isn't always possible to tweak your query to return fewer results, but sometimes it is possible to do a more precise query first, thus making a broader query unnecessary. For example, a search for an individual in their expected jurisdiction will be faster than doing it in the entire corpus. This will benefit from profiling in your use case and application.

**Git Forum** to handle issues: https://github.com/freelawproject/courtlistener/discussions

**Comment by eshanprashar** [comment]
### Judge ID with history of positions (when did they become a judge) to have a cutoff time 

- [x] Decision: since people are embedded in positions, makes more sense to make _position requests_ 
- [x] Obtained results for the first 100 positions
- [x] Wrote to CL team to seek help with throttling 

**Next steps:**
- [ ] With the team: Discuss how to save output and what to do with it 
- [ ] Obtain for all pages using brute force approach
- [ ] Make code more efficient using parallelization

**Comment by eshanprashar** [comment]
### What kind of investments did a judge have?
Initial findings for positions and investments covered in [these slides](https://docs.google.com/presentation/d/1JfAUypQepARoCEWFQl8w_bpZcZQxi5lPt7FChbAs5H8/edit?usp=sharing)

**Comment by eshanprashar** [comment]
### What kind of company cases did judges sit on?
Defendent / Plaintiff information to check
